### ISSUE TITLE
Gem seems to not be working with Fog 1.9.0

### ISSUE THREAD

**Issue by marcgg** [AssetSync/asset_sync#158]
Running precompile fails immediately when trying to sync.

```
AssetSync: Syncing.
rake aborted!
undefined method `headers' for #<Hash:0x007fedfc406798>
/Users/marcgg/.rvm/gems/ruby-1.9.3-p327@drivy/gems/fog-1.9.0/lib/fog/aws/storage.rb:403:in `rescue in request'
/Users/marcgg/.rvm/gems/ruby-1.9.3-p327@drivy/gems/fog-1.9.0/lib/fog/aws/storage.rb:400:in `request'
/Users/marcgg/.rvm/gems/ruby-1.9.3-p327@drivy/gems/fog-1.9.0/lib/fog/aws/requests/storage/get_bucket.rb:52:in `get_bucket'
/Users/marcgg/.rvm/gems/ruby-1.9.3-p327@drivy/gems/fog-1.9.0/lib/fog/aws/models/storage/directories.rb:24:in `get'
/Users/marcgg/.rvm/gems/ruby-1.9.3-p327@drivy/gems/asset_sync-0.5.4/lib/asset_sync/storage.rb:18:in `bucket'
/Users/marcgg/.rvm/gems/ruby-1.9.3-p327@drivy/gems/asset_sync-0.5.4/lib/asset_sync/storage.rb:77:in `get_remote_files'
/Users/marcgg/.rvm/gems/ruby-1.9.3-p327@drivy/gems/asset_sync-0.5.4/lib/asset_sync/storage.rb:163:in `upload_files'
/Users/marcgg/.rvm/gems/ruby-1.9.3-p327@drivy/gems/asset_sync-0.5.4/lib/asset_sync/storage.rb:177:in `sync'
/Users/marcgg/.rvm/gems/ruby-1.9.3-p327@drivy/gems/asset_sync-0.5.4/lib/asset_sync/asset_sync.rb:35:in `sync'
/Users/marcgg/.rvm/gems/ruby-1.9.3-p327@drivy/gems/asset_sync-0.5.4/lib/tasks/asset_sync.rake:3:in `block in <top (required)>'
Tasks: TOP => assets:precompile:nondigest
(See full trace by running task with --trace)
rake aborted!
```

It was working fine with fog 1.8.0.
I'm not sure if it's a problem with fog or asset_sync, but if it is not working with the latest version of fog, maybe it'd be interesting to mention it somewhere or specify a fog version as dependency.

thanks!
